<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_field_in_card</name>
   <tag></tag>
   <elementGuidId>eebc9b9a-be5c-4e1a-b584-75d636d1e2db</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'sk-tab-list')]/div/div/table/tbody/tr[3]/td/table[1]/tbody/tr[2]/td[2]/div</value>
   </webElementProperties>
</WebElementEntity>
