<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_save_approve</name>
   <tag></tag>
   <elementGuidId>7e76f054-7777-4a9a-8548-da3b42b68f83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.x-toolbar .sk-tab-btn-save-approve</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class, 'x-btn sk-tab-btn sk-tab-btn-save x-box-item x-toolbar-item x-btn-default-toolbar-small x-icon-text-left x-btn-icon-text-left x-btn-default-toolbar-small-icon-text-left')]/em/button/span[contains(@class, 'icon-commit')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.x-toolbar .sk-tab-btn-save-approve</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-1239-btnInnerEl</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-inner</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Одобрить</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-1239-btnInnerEl&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.x-toolbar .sk-tab-btn-save-approve</value>
   </webElementProperties>
</WebElementEntity>
