<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_text_field</name>
   <tag></tag>
   <elementGuidId>7b9e3477-9f66-4d79-a5a8-d8eb43b65f15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'form__col-1')][11]//input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,'form__col-1')][11]//input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'form__col-1')][11]//input</value>
   </webElementProperties>
</WebElementEntity>
