<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_multiline_text_field</name>
   <tag></tag>
   <elementGuidId>350a91f6-2b75-44b2-b24d-2c5cdffc8ed7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'form__col-1')][7]//textarea</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,'form__col-1')][7]//textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'form__col-1')][7]//textarea</value>
   </webElementProperties>
</WebElementEntity>
