<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_checkbox</name>
   <tag></tag>
   <elementGuidId>7044971c-1963-4e26-86fb-ece828d47a94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'form__col-1')][2]//label[contains(@class,'form__checkbox-trigger')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,'form__col-1')][2]//label[contains(@class,'form__checkbox-trigger')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form__checkbox-trigger</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>check-galochka_b4d62b70d4f00eb957001d54e29f72ed</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'form__col-1')][2]//label[contains(@class,'form__checkbox-trigger')]</value>
   </webElementProperties>
</WebElementEntity>
