<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_drop_down_list</name>
   <tag></tag>
   <elementGuidId>79aaa07b-501e-4e93-815c-79da4b5e1213</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.form__input--select</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'form__cols-wrap')]//div[contains(@class,'form__col-1')][1]//div[contains(@class,'form__input--select')]/span[1]/span[1]/span/span[2]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,'form__cols-wrap')]//div[contains(@class,'form__col-1')][1]//div[contains(@class,'form__input--select')]/span[1]/span[1]/span/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-vypadayuschij-spisok_b4d62b70d4f00eb957001d54e29f72ed-container</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'form__cols-wrap')]//div[contains(@class,'form__col-1')][1]//div[contains(@class,'form__input--select')]/span[1]/span[1]/span/span[2]</value>
   </webElementProperties>
</WebElementEntity>
