<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_second_left_banner</name>
   <tag></tag>
   <elementGuidId>fb0634b6-7e92-4d5d-93c5-90ab278420b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'b-bannerleft')][2]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,'b-bannerleft')][2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'b-bannerleft')][2]</value>
   </webElementProperties>
</WebElementEntity>
