<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_error_validation</name>
   <tag></tag>
   <elementGuidId>1f176c74-a217-4caa-9672-0518cd9e5100</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//form/div[contains(@class,'form__cols-wrap')]/div[contains(@class,'form__col-1')][9]/div[contains(@class,'form__errors')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form/div[contains(@class,'form__cols-wrap')]/div[contains(@class,'form__col-1')][9]/div[contains(@class,'form__errors')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.form__errors</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//form/div[contains(@class,'form__cols-wrap')]/div[contains(@class,'form__col-1')][9]/div[contains(@class,'form__errors')]</value>
   </webElementProperties>
</WebElementEntity>
