<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_articles</name>
   <tag></tag>
   <elementGuidId>cd45b21c-0ee7-41f8-8895-1ec07b5cbc77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,'x-tab sk-tabHeader-skewer\build\Adm\Articles\Module x-box-item x-tab-default x-top x-tab-top x-tab-default-top x-noicon x-tab-noicon x-tab-default-noicon')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tab-1170-btnInnerEl</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-tab-inner</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Статьи</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'x-tab sk-tabHeader-skewer\build\Adm\Articles\Module x-box-item x-tab-default x-top x-tab-top x-tab-default-top x-noicon x-tab-noicon x-tab-default-noicon')]</value>
   </webElementProperties>
</WebElementEntity>
