<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_number_of_section</name>
   <tag></tag>
   <elementGuidId>aa5a74d1-5fdf-48b8-bfd6-03f7b113b3c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//table[contains(@class,'x-grid-table x-grid-table-resizer')]//tr[last()]/td[2]/div[contains(@class,'x-grid-cell-inner x-unselectable')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[contains(@class,'x-grid-table x-grid-table-resizer')]//tr[last()]/td[2]/div[contains(@class,'x-grid-cell-inner x-unselectable')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-grid-cell-inner x-unselectable</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ext-gen1415</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>325</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//table[contains(@class,'x-grid-table x-grid-table-resizer')]//tr[last()]/td[2]/div[contains(@class,'x-grid-cell-inner x-unselectable')]</value>
   </webElementProperties>
</WebElementEntity>
