<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_edit_section</name>
   <tag></tag>
   <elementGuidId>5e7e28af-71a3-4840-b9e6-a47301ee9710</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'sk-tree')]/div[contains(@class,'x-toolbar x-toolbar-default x-docked x-docked-top x-toolbar-docked-top x-toolbar-default-docked-top x-box-layout-ct x-docked-noborder-right x-docked-noborder-left')]//div[contains(@class,'x-box-inner')]/div[contains(@class,'sk-section-add')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,'sk-tree')]/div[contains(@class,'x-toolbar x-toolbar-default x-docked x-docked-top x-toolbar-docked-top x-toolbar-default-docked-top x-box-layout-ct x-docked-noborder-right x-docked-noborder-left')]//div[contains(@class,'x-box-inner')]/div[contains(@class,'sk-section-add')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-1047-btnInnerEl</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-inner</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Добавить</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'sk-tree')]/div[contains(@class,'x-toolbar x-toolbar-default x-docked x-docked-top x-toolbar-docked-top x-toolbar-default-docked-top x-box-layout-ct x-docked-noborder-right x-docked-noborder-left')]//div[contains(@class,'x-box-inner')]/div[contains(@class,'sk-section-add')]</value>
   </webElementProperties>
</WebElementEntity>
