#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);

// fcgi doesn't have STDIN and STDOUT defined by default
defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));

require_once(__DIR__.'/config/constants.generated.php');

defined('RELEASEPATH') OR define('RELEASEPATH', ROOTPATH.'skewer/');

require_once(RELEASEPATH . '/../vendor/autoload.php');
require_once(RELEASEPATH . '/../skewer/app/Yii.php');

require_once(RELEASEPATH.'/config/constants.php');

require_once(RELEASEPATH . '/../skewer/app/ConsoleApp.php');
$config = require(RELEASEPATH . '/config/console.php');

$application = new \skewer\app\ConsoleApp($config);
$exitCode = $application->run();
exit($exitCode);
