<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_hidden_field_on_page</name>
   <tag></tag>
   <elementGuidId>9d28e72c-e6ff-44ce-8f2b-c2df97c7aed4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[contains(@class,'form__cptch_country')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@class,'form__cptch_country')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[contains(@class,'form__cptch_country')]</value>
   </webElementProperties>
</WebElementEntity>
