<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_private_policy</name>
   <tag></tag>
   <elementGuidId>62984369-964b-4d25-abd8-c35719b814ca</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form__checkbox-trigger</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>check_ok_81caf4ea2f0bbf6adad4548fcce4d68b</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_81caf4ea2f0bbf6adad4548fcce4d68b&quot;)/div[@class=&quot;form__cols-wrap&quot;]/div[@class=&quot;form__col-1&quot;]/div[@class=&quot;form__item form__item--checkboxes form__item--agree&quot;]/div[@class=&quot;form__input-wrap&quot;]/div[@class=&quot;form__input form__input--checkbox&quot;]/div[@class=&quot;form__checkbox&quot;]/label[@class=&quot;form__checkbox-trigger&quot;]</value>
   </webElementProperties>
</WebElementEntity>
