<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_form_checkbox_trigger</name>
   <tag></tag>
   <elementGuidId>b1ea022d-a783-4553-abe2-d1463301d415</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form__checkbox-trigger</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>check_ok_faed6ce99aa5107c25f94677c9c62f75</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_faed6ce99aa5107c25f94677c9c62f75&quot;)/div[@class=&quot;form__cols-wrap&quot;]/div[@class=&quot;form__col-1&quot;]/div[@class=&quot;form__item form__item--checkboxes form__item--agree&quot;]/div[@class=&quot;form__input-wrap&quot;]/div[@class=&quot;form__input form__input--checkbox&quot;]/div[@class=&quot;form__checkbox&quot;]/label[@class=&quot;form__checkbox-trigger&quot;]</value>
   </webElementProperties>
</WebElementEntity>
