<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_text_the_announcment_on_main</name>
   <tag></tag>
   <elementGuidId>81d275a3-12de-4da8-9487-65ff5a1941ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'column__center-indent')]
//div[contains(@class,'news__item')][1]
//div[contains(@class,'b-editor')]
</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,'column__center-indent')]
//div[contains(@class,'news__item')][1]
//div[contains(@class,'b-editor')]
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Краткое описание акции</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'column__center-indent')]
//div[contains(@class,'news__item')][1]
//div[contains(@class,'b-editor')]
</value>
   </webElementProperties>
</WebElementEntity>
