<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_text_of_section</name>
   <tag></tag>
   <elementGuidId>b307a578-2a83-4eb7-984e-13b880ba0153</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//body[count(. | //DIV[@ref_element = 'Object Repository/CMS/Sections/TextOfSection/iframe_text_of_section']) = count(//DIV[@ref_element = 'Object Repository/CMS/Sections/TextOfSection/iframe_text_of_section'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/CMS/Sections/TextOfSection/iframe_text_of_section</value>
   </webElementProperties>
</WebElementEntity>
