<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_text_of_the_announcement</name>
   <tag></tag>
   <elementGuidId>dd49530c-2b48-4b50-8276-86f0d9d108d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'column__center-indent')]
//div[contains(@class,'news__item')][1]
//div[contains(@class,'b-editor')]
</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,'column__center-indent')]
//div[contains(@class,'news__item')][1]
//div[contains(@class,'b-editor')]
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>b-editor</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
 qasdasd </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'column__center-indent')]
//div[contains(@class,'news__item')][1]
//div[contains(@class,'b-editor')]
</value>
   </webElementProperties>
</WebElementEntity>
