<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_news</name>
   <tag></tag>
   <elementGuidId>e5e15812-4cea-4036-98dc-d7aa9de51419</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'x-tab sk-tabHeader-skewer\build\Adm\News\Module x-box-item x-tab-default x-top x-tab-top x-tab-default-top x-noicon x-tab-noicon x-tab-default-noicon')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,'x-tab sk-tabHeader-skewer\build\Adm\News\Module x-box-item x-tab-default x-top x-tab-top x-tab-default-top x-noicon x-tab-noicon x-tab-default-noicon')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tab-1260-btnInnerEl</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-tab-inner</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Новости</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'x-tab sk-tabHeader-skewer\build\Adm\News\Module x-box-item x-tab-default x-top x-tab-top x-tab-default-top x-noicon x-tab-noicon x-tab-default-noicon')]</value>
   </webElementProperties>
</WebElementEntity>
