<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_save</name>
   <tag></tag>
   <elementGuidId>d5676ef8-d6d6-4c3c-a760-4cee5e91a584</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.sk-tab-btn-save</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,'x-panel sk-tab-skewer\build\Adm\News\Module x-tabpanel-child x-panel-default x-body-masked')]//div[contains(@class,'x-btn sk-tab-btn sk-tab-btn-save x-box-item x-toolbar-item x-btn-default-toolbar-small x-icon-text-left x-btn-icon-text-left x-btn-default-toolbar-small-icon-text-left')]//button[contains(@class,'x-btn-center')]//span[contains(@class,'icon-save')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'x-panel sk-tab-skewer\build\Adm\News\Module x-tabpanel-child x-panel-default x-body-masked')]//div[contains(@class,'x-btn sk-tab-btn sk-tab-btn-save x-box-item x-toolbar-item x-btn-default-toolbar-small x-icon-text-left x-btn-icon-text-left x-btn-default-toolbar-small-icon-text-left')]//button[contains(@class,'x-btn-center')]//span[contains(@class,'icon-save')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-1386-btnInnerEl</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-inner</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Сохранить</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'x-panel sk-tab-skewer\build\Adm\News\Module x-tabpanel-child x-panel-default x-body-masked')]//div[contains(@class,'x-btn sk-tab-btn sk-tab-btn-save x-box-item x-toolbar-item x-btn-default-toolbar-small x-icon-text-left x-btn-icon-text-left x-btn-default-toolbar-small-icon-text-left')]//button[contains(@class,'x-btn-center')]//span[contains(@class,'icon-save')]</value>
   </webElementProperties>
</WebElementEntity>
