<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_count_goods_cart</name>
   <tag></tag>
   <elementGuidId>84e2d4a0-5a0a-49c6-b4b0-20b2745a1fa9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,'cart__table')]
//div[contains(@class,'cart__item js-cart__row')][1]
//div[contains(@class,'cart__count-catalog b-catalogbox b-catalogbox-cart')]
//input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>19</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>js_cart_amount</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;g-js&quot;]/body[1]/div[@class=&quot;l-layout&quot;]/div[@class=&quot;layout__wrap&quot;]/div[@class=&quot;l-main l-main--content&quot;]/div[@class=&quot;main__wrapper&quot;]/div[@class=&quot;column column_lc column_cr&quot;]/div[@class=&quot;column__center&quot;]/div[@class=&quot;column__center-indent&quot;]/div[@class=&quot;b-cart&quot;]/div[@class=&quot;js_cart_content cart__content&quot;]/div[@class=&quot;cart__table&quot;]/div[@class=&quot;cart__item js-cart__row&quot;]/div[@class=&quot;cart__count&quot;]/div[@class=&quot;cart__count-catalog b-catalogbox b-catalogbox-cart&quot;]/div[@class=&quot;js_catalogbox_inputbox catalogbox__inputbox&quot;]/input[@class=&quot;js_cart_amount&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <value>//input[@value='1']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Сумма:'])[1]/preceding::input[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div/input</value>
   </webElementXpaths>
</WebElementEntity>
