<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_integration</name>
   <tag></tag>
   <elementGuidId>cb6770cf-43d9-4d4a-8a16-4e68e03ed4b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//section/div/div[contains(@class,'b-section__col')][1]/nav/ul/li[10]/a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section/div/div[contains(@class,'b-section__col')][1]/nav/ul/li[10]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Интеграция</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//section/div/div[contains(@class,'b-section__col')][1]/nav/ul/li[10]/a</value>
   </webElementProperties>
</WebElementEntity>
