<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_integration_parametrs</name>
   <tag></tag>
   <elementGuidId>1dd7d18b-7590-4e8d-87bc-ecc9af8d47c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section/div/div[contains(@class,'b-section__col')][1]/nav/ul/li[10]/ul/li[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//section/div/div[contains(@class,'b-section__col')][1]/nav/ul/li[10]/ul/li[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/settings/link</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Параметры интеграции</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//section/div/div[contains(@class,'b-section__col')][1]/nav/ul/li[10]/ul/li[1]</value>
   </webElementProperties>
</WebElementEntity>
