<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_text_field</name>
   <tag></tag>
   <elementGuidId>d4bc3c62-2639-4a31-9fbd-8e9f06a6b92f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'form__cols-wrap')]/div[contains(@class,'form__col-1')][11]/div/div[2]/input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,'form__cols-wrap')]/div[contains(@class,'form__col-1')][11]/div/div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'form__cols-wrap')]/div[contains(@class,'form__col-1')][11]/div/div[2]/input</value>
   </webElementProperties>
</WebElementEntity>
