<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_password</name>
   <tag></tag>
   <elementGuidId>d1edc79f-6cb1-4d0b-98e3-bddeb24b67df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'form__cols-wrap')]/div[contains(@class,'form__col-1')][8]/div/div[2]/input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,'form__cols-wrap')]/div[contains(@class,'form__col-1')][8]/div/div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'form__cols-wrap')]/div[contains(@class,'form__col-1')][8]/div/div[2]/input</value>
   </webElementProperties>
</WebElementEntity>
