<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_checkbox</name>
   <tag></tag>
   <elementGuidId>8b62cc65-a065-4d25-890f-7b6e5d7cf4f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'form__cols-wrap')]/div[contains(@class,'form__col-1')][2]/div/div[2]/div/div[1]/label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,'form__cols-wrap')]/div[contains(@class,'form__col-1')][2]/div/div[2]/div/div[1]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form__checkbox-trigger</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>check-galochka_e3995efd13351709b74310973283bda5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'form__cols-wrap')]/div[contains(@class,'form__col-1')][2]/div/div[2]/div/div[1]/label</value>
   </webElementProperties>
</WebElementEntity>
