<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_value_2_checkbox_group</name>
   <tag></tag>
   <elementGuidId>61aff7ed-4dc4-4b9d-a5f7-5ea58e56ff87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'form__cols-wrap')]/div[contains(@class,'form__col-1')][3]/div/div[2]/div[2]/div/label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,'form__cols-wrap')]/div[contains(@class,'form__col-1')][3]/div/div[2]/div[2]/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form__checkbox-trigger</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>chck-grp-gruppa-galochek1_e3995efd13351709b74310973283bda5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'form__cols-wrap')]/div[contains(@class,'form__col-1')][3]/div/div[2]/div[2]/div/label</value>
   </webElementProperties>
</WebElementEntity>
