<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_drop_down_list</name>
   <tag></tag>
   <elementGuidId>b84bebba-b799-4b18-932b-d6cff3bd7628</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.select2-selection__arrow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,'form__cols-wrap')]/div[contains(@class,'form__col-1')][1]/div/div[2]/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.select2-selection__arrow</value>
   </webElementProperties>
</WebElementEntity>
