<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_email_order_profile</name>
   <tag></tag>
   <elementGuidId>494b3509-2a7c-450e-9872-bddc58e19983</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,'cabbox__item')]
//div[contains(@class,'cabbox__sidebox')]
//tbody
/tr[5]
/td[2]
/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>123@test.test</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;g-js&quot;]/body[1]/div[@class=&quot;l-layout&quot;]/div[@class=&quot;layout__wrap&quot;]/div[@class=&quot;l-main l-main--content&quot;]/div[@class=&quot;main__wrapper&quot;]/div[@class=&quot;column column_lc&quot;]/div[@class=&quot;column__center&quot;]/div[@class=&quot;column__center-indent&quot;]/div[@class=&quot;b-cabbox b-cabbox-detal&quot;]/div[@class=&quot;b-tab&quot;]/div[1]/div[@class=&quot;cabbox__item&quot;]/div[@class=&quot;cabbox__sidebox&quot;]/div[1]/table[@class=&quot;cabbox__table2&quot;]/tbody[1]/tr[5]/td[2]/span[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E-mail:'])[1]/following::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Телефон:'])[1]/following::span[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Тип оплаты:'])[1]/preceding::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Оплата on-line'])[1]/preceding::span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//tr[5]/td[2]/span</value>
   </webElementXpaths>
</WebElementEntity>
