<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_new_news_on_main</name>
   <tag></tag>
   <elementGuidId>717e593f-00a8-4ed2-85aa-c84ca1e85fdb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,'column__center-indent')]
//div[contains(@class,'b-news b-news--list')]
//div[contains(@class,'news__item')][1]
//a[contains(@class,'news__link')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'column__center-indent')]
//div[contains(@class,'b-news b-news--list')]
//div[contains(@class,'news__item')][1]
/div[contains(@class,'news__wrap')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>news__link</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/akcii-i-specpredlozhenija/samodostatochnyj-postmodernizm-metodologiya-i-osobennosti/</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Акция 1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'column__center-indent')]
//div[contains(@class,'b-news b-news--list')]
//div[contains(@class,'news__item')][1]
/div[contains(@class,'news__wrap')]</value>
   </webElementProperties>
</WebElementEntity>
