<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_tab_form</name>
   <tag></tag>
   <elementGuidId>f22ff73e-bca3-45c2-aa5c-709b75352694</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div[class='sk-tabHeader-skewer\build\Adm\Forms\Module']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-tab sk-tabHeader-skewer\\build\\Adm\\Forms\\Module x-box-item x-tab-default x-top x-tab-top x-tab-default-top x-noicon x-tab-noicon x-tab-default-noicon x-over x-tab-over x-tab-default-over over</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.sk-tabHeader-skewer\\build\\Adm\\Forms\\Module</value>
   </webElementProperties>
</WebElementEntity>
