<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_stars</name>
   <tag></tag>
   <elementGuidId>695d73f1-7a38-4365-ab40-9ce5ace5c9c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//body/div[contains(@class,'x-boundlist x-boundlist-floating x-boundlist-default x-layer')][2]/div[contains(@class,'list-ct')]/ul/li</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/div[contains(@class,'x-boundlist x-boundlist-floating x-boundlist-default x-layer')][2]/div[contains(@class,'list-ct')]/ul/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-boundlist-item x-boundlist-selected x-boundlist-item-over</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ext-gen1436</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Звезды</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body/div[contains(@class,'x-boundlist x-boundlist-floating x-boundlist-default x-layer')][2]/div[contains(@class,'list-ct')]/ul/li</value>
   </webElementProperties>
</WebElementEntity>
