<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_collection</name>
   <tag></tag>
   <elementGuidId>2fdfffd6-a438-41c7-a15b-9369a09f4ee9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'sk-catalog')]//tbody/tr[5]/td[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'sk-catalog')]//tbody/tr[5]/td[2]/div</value>
   </webElementProperties>
</WebElementEntity>
