<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_answer_on_site</name>
   <tag></tag>
   <elementGuidId>e9c65304-082a-4d95-8720-2db39b77e717</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,'guestbox__item')]
//div[contains(@class,'b-editor')]
//div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'b-faq')]
//div[contains(@class,'faq__rightside')]
//div[contains(@class,'b-editor')]
/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ответ: 1 </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'b-faq')]
//div[contains(@class,'faq__rightside')]
//div[contains(@class,'b-editor')]
/div</value>
   </webElementProperties>
</WebElementEntity>
