<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_questoin_in_faq_on_site</name>
   <tag></tag>
   <elementGuidId>30b7bf5d-124c-4e35-ba91-e8739ec6d137</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'guestbox__rightside')]
//div[contains(@class,'b-editor')][1]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,'guestbox__rightside')]
//div[contains(@class,'b-editor')][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>b-editor</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'guestbox__rightside')]
//div[contains(@class,'b-editor')][1]</value>
   </webElementProperties>
</WebElementEntity>
