<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_review_sandwich</name>
   <tag></tag>
   <elementGuidId>5088c03d-6d8e-41e8-acc1-4509a65b23b3</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/pokupatelyu/otzyvy/</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
 Отзывы
 </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;g-js&quot;]/body[@class=&quot;g-ov-h&quot;]/div[@class=&quot;l-sidebar-block l-sidebar-block--left hide-on-desktop show-on-tablet-l js-sidebar-block l-sidebar-block--open&quot;]/div[@class=&quot;b-sidebar&quot;]/div[@class=&quot;sidebar__content&quot;]/div[@class=&quot;b-sidebar-menu b-sidebar-menu--topmenu&quot;]/ul[@class=&quot;sidebar-menu__level-1&quot;]/li[@class=&quot;sidebar-menu__item-1 sidebar-menu__item-1--haschild js-sidebarmenu-item sidebar-menu__item--open&quot;]/ul[@class=&quot;sidebar-menu__level-2 js-sidebarmenu-content&quot;]/li[@class=&quot;sidebar-menu__item-2 sidebar-menu__item-2--last js-sidebarmenu-item&quot;]/span[@class=&quot;js-sidebarmenu-achor-wrap&quot;]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
