<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_reviews</name>
   <tag></tag>
   <elementGuidId>c16e720d-7184-4e4e-baca-261f433739ee</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/pokupatelyu/otzyvy/</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
 Отзывы 
 
 </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;g-js&quot;]/body[1]/div[@class=&quot;l-layout&quot;]/div[@class=&quot;layout__wrap&quot;]/div[@class=&quot;l-header&quot;]/div[@class=&quot;header__wrapper js_dnd_wraper&quot;]/div[@class=&quot;b-header hide-on-tablet hide-on-mobile&quot;]/div[@class=&quot;b-sevice&quot;]/ul[@class=&quot;sevice__level-1&quot;]/li[@class=&quot;sevice__item-1 sevice__item-id-279 sevice__item-1--haschild&quot;]/ul[@class=&quot;sevice__level-2&quot;]/li[@class=&quot;sevice__item-2 last2&quot;]/span[1]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
