<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_form_checkbox_private_policy</name>
   <tag></tag>
   <elementGuidId>ee50043a-0674-41da-a776-d2cccf866426</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//label[@class = 'form__checkbox-trigger']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form__checkbox-trigger</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>check_ok_00853b231cfed06cd345b62514180eef</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_00853b231cfed06cd345b62514180eef&quot;)/div[@class=&quot;form__cols-wrap&quot;]/div[@class=&quot;form__col-1&quot;]/div[@class=&quot;form__item form__item--checkboxes form__item--agree&quot;]/div[@class=&quot;form__input-wrap&quot;]/div[@class=&quot;form__input form__input--checkbox&quot;]/div[@class=&quot;form__checkbox&quot;]/label[@class=&quot;form__checkbox-trigger&quot;]</value>
   </webElementProperties>
</WebElementEntity>
