<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_email</name>
   <tag></tag>
   <elementGuidId>18e14e6b-736d-48a8-a078-ef95b9ee7aab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[@id = 'ext-comp-1189-body' and (text() = 'Логин:Пароль:Подтверждение пароля:Политика доступа:Это поле обязательно для заполненияИмя пользователя:E-mail пользователя:Активен:' or . = 'Логин:Пароль:Подтверждение пароля:Политика доступа:Это поле обязательно для заполненияИмя пользователя:E-mail пользователя:Активен:')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ext-comp-1189-body</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-panel-body  x-panel-body-default x-panel-body-default x-docked-noborder-top x-docked-noborder-right x-docked-noborder-bottom x-docked-noborder-left</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Логин:Пароль:Подтверждение пароля:Политика доступа:Это поле обязательно для заполненияИмя пользователя:E-mail пользователя:Активен:</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ext-comp-1189-body&quot;)</value>
   </webElementProperties>
</WebElementEntity>
