<?php

namespace unit\base\site;

use skewer\base\site\Type;
use skewer\base\SysVar;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2015-02-05 at 10:03:41.
 */
class TypeTest extends \Codeception\Test\Unit
{
    /**
     * @var Type
     */
    protected $object;

    private $sOldVal = '';

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Type();
        $this->sOldVal = $this->object->getAlias();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        SysVar::set('site_type', $this->sOldVal);
    }

    /**
     * @covers \skewer\base\site\Type::getAlias
     */
    public function testGetAlias()
    {
        SysVar::set('site_type', 'catalog');
        $this->assertInternalType('string', $this->object->getAlias(), 'Не истина!');
        $this->assertEquals('catalog', $this->object->getAlias());
    }

    /**
     * @covers \skewer\base\site\Type::isInfo
     */
    public function testIsInfo()
    {
        SysVar::set('site_type', 'info');
        $this->assertTrue($this->object->isInfo(), 'Сайт не информационный!');
    }

    /**
     * @covers \skewer\base\site\Type::hasCatalogModule
     */
    public function testHasCatalogModule()
    {
        SysVar::set('site_type', 'info');
        $this->assertTrue(!$this->object->hasCatalogModule(), 'Сайт не информационттый');
    }

    /**
     * @covers \skewer\base\site\Type::isCatalog
     */
    public function testIsCatalog()
    {
        SysVar::set('site_type', 'catalog');
        $this->assertTrue($this->object->isCatalog(), 'Сайт не каталожный!');
    }

    /**
     * @covers \skewer\base\site\Type::isShop
     */
    public function testIsShop()
    {
        // Remove the following lines when you implement this test.
        SysVar::set('site_type', 'shop');
        $this->assertTrue($this->object->isShop(), 'Сайт не магазин!');
    }
}
