<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_section</name>
   <tag></tag>
   <elementGuidId>05c732a0-7209-4492-ad75-e24dd080110d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'sk-tab-skewer\build\Adm\CategoryViewer\Module')]//div[contains(@class,'sk-tab-form')]/div/div[5]/div[1]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'sk-tab-skewer\build\Adm\CategoryViewer\Module')]//div[contains(@class,'sk-tab-form')]/div/div[5]/div[1]/input</value>
   </webElementProperties>
</WebElementEntity>
