<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_new_faq</name>
   <tag></tag>
   <elementGuidId>aebc0552-5bc4-4f9f-87b2-9adcd4e2ba87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.sk-tab-btn-show</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,'x-btn sk-tab-btn sk-tab-btn-new x-box-item x-toolbar-item x-btn-default-toolbar-small x-icon-text-left x-btn-icon-text-left x-btn-default-toolbar-small-icon-text-left')]
//button[contains(@class,'x-btn-center')]
//span[contains(@class,'x-btn-inner')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'x-btn sk-tab-btn sk-tab-btn-new x-box-item x-toolbar-item x-btn-default-toolbar-small x-icon-text-left x-btn-icon-text-left x-btn-default-toolbar-small-icon-text-left')]
//button[contains(@class,'x-btn-center')]
//span[contains(@class,'x-btn-inner')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-1261-btnInnerEl</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-inner</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Добавить</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'x-btn sk-tab-btn sk-tab-btn-new x-box-item x-toolbar-item x-btn-default-toolbar-small x-icon-text-left x-btn-icon-text-left x-btn-default-toolbar-small-icon-text-left')]
//button[contains(@class,'x-btn-center')]
//span[contains(@class,'x-btn-inner')]</value>
   </webElementProperties>
</WebElementEntity>
