<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_question_faq</name>
   <tag></tag>
   <elementGuidId>1c104661-ae9c-4427-ac28-e049a81ba1dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,'x-panel sk-tab-list x-grid x-box-item x-panel-default')]//tr[contains(@class,'x-grid-row')][1]/td[contains(@class,'x-grid-cell')][3]/div[contains(@class,'x-grid-cell-inner x-unselectable')][1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'x-panel sk-tab-list x-grid x-box-item x-panel-default')]//tr[contains(@class,'x-grid-row')][1]/td[contains(@class,'x-grid-cell')][3]/div[contains(@class,'x-grid-cell-inner x-unselectable')][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-grid-cell-inner x-unselectable</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ext-gen1427</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>123</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'x-panel sk-tab-list x-grid x-box-item x-panel-default')]//tr[contains(@class,'x-grid-row')][1]/td[contains(@class,'x-grid-cell')][3]/div[contains(@class,'x-grid-cell-inner x-unselectable')][1]</value>
   </webElementProperties>
</WebElementEntity>
