<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_review_status_n1</name>
   <tag></tag>
   <elementGuidId>a05cf08d-2d3a-4073-aa4c-6f2374645fd5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,'sk-tab-skewer\build\Adm\GuestBook\Module')]//table[contains(@class,'x-grid-table x-grid-table-resizer')]//tr[contains(@class,'x-grid-row')][1]//td[contains(@class,'sk-list-status_text')]/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'sk-tab-skewer\build\Adm\GuestBook\Module')]//table[contains(@class,'x-grid-table x-grid-table-resizer')]//tr[contains(@class,'x-grid-row')][1]//td[contains(@class,'sk-list-status_text')]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-grid-cell-inner x-unselectable</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ext-gen1668</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Одобрен</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'sk-tab-skewer\build\Adm\GuestBook\Module')]//table[contains(@class,'x-grid-table x-grid-table-resizer')]//tr[contains(@class,'x-grid-row')][1]//td[contains(@class,'sk-list-status_text')]/div</value>
   </webElementProperties>
</WebElementEntity>
