<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_save_review</name>
   <tag></tag>
   <elementGuidId>6c47f3e0-bef0-48df-ae6c-82179b7818c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'x-panel sk-tab-skewer\build\Adm\GuestBook\Module x-tabpanel-child x-panel-default x-body-masked')]//div[contains(@class,'x-btn sk-tab-btn sk-tab-btn-save')][1]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,'x-panel sk-tab-skewer\build\Adm\GuestBook\Module x-tabpanel-child x-panel-default x-body-masked')]//div[contains(@class,'x-btn sk-tab-btn sk-tab-btn-save')][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-1237-btnInnerEl</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-inner</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Сохранить</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'x-panel sk-tab-skewer\build\Adm\GuestBook\Module x-tabpanel-child x-panel-default x-body-masked')]//div[contains(@class,'x-btn sk-tab-btn sk-tab-btn-save')][1]</value>
   </webElementProperties>
</WebElementEntity>
