<?php

namespace unit\helpers;

use skewer\helpers\Transliterate;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-12-26 at 18:00:12.
 */
class TransliterateTest extends \Codeception\Test\Unit
{
    /**
     * Проверка транслитерации.
     *
     * @dataProvider providerChange
     * @covers \skewer\helpers\Transliterate::change
     *
     * @param mixed $sOut
     * @param mixed $sIn
     * @param mixed $sToLower
     */
    public function testChange($sOut, $sIn, $sToLower = true)
    {
        $this->assertSame($sOut, Transliterate::change($sIn, $sToLower));
    }

    /**
     * Провайдер данных для тестирования транслитерации.
     *
     * @return array
     */
    public function providerChange()
    {
        return [
            ['privet, medved', 'Привет, Медвед'],
            ['Privet, Medved', 'Привет, Медвед', false],
            ['spec simvoly&%"', 'Спец символы&%\'`"ьЪ'],
        ];
    }

    /**
     * Тест замены запрещенных символов.
     *
     * @covers \skewer\helpers\Transliterate::changeDeprecated
     */
    public function testChangeDeprecated()
    {
        $this->assertSame('q---wr---t-yuiop--123', Transliterate::changeDeprecated('q%()wr-&*t yuiop@`123'));
    }

    /**
     * Тест укорачивания последовательностей разделителей.
     *
     * @covers \skewer\helpers\Transliterate::mergeDelimiters
     */
    public function testMergeDelimiters()
    {
        $this->assertSame('-jkas-da-123-', Transliterate::mergeDelimiters('----jkas-da-----123----'));
    }

    /**
     * Тест запроса разделителей.
     *
     * @covers \skewer\helpers\Transliterate::getDelimiter
     */
    public function testGetDelimiter()
    {
        $this->assertSame('-', Transliterate::getDelimiter());
    }

    /**
     * Тест установки разделитетей.
     *
     * @covers \skewer\helpers\Transliterate::setDelimiter
     */
    public function testSetDelimiter()
    {
        Transliterate::setDelimiter('=');
        $this->assertSame('=', Transliterate::getDelimiter());
        Transliterate::setDelimiter('-');
        $this->assertSame('-', Transliterate::getDelimiter());
    }

    /**
     * Переводим строку с пробелами и поджеркаваниями в верблюжий стиль.
     *
     * @covers \skewer\helpers\Transliterate::toCamelCase
     */
    public function testToCamelCase()
    {
        $this->assertSame('AsdVbsVw', Transliterate::toCamelCase('asd_vbs_vw'));
    }
}
