version: '2'
volumes:
  mysql_data: {}
services:
  #######################################
  # PHP application Docker container
  #######################################
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    links:
      - mail
      - mysql
    ports:
      - "80:80"
      - "8443:443"
      - "10022:22"
    volumes:
      - .:/app/
      - ./:/docker/
    volumes_from:
      - storage
    env_file:
      - docker/etc/environment.yml
      - docker/etc/environment.development.yml

  #######################################
  # MySQL server
  #######################################
  mysql:
    build:
      context: docker/mysql/
      #dockerfile: MySQL-5.5.Dockerfile
      dockerfile: ../../mysql/MySQL-5.6.Dockerfile
      #dockerfile: MySQL-5.7.Dockerfile
    volumes_from:
      - storage
    volumes:
      - mysql_data:/var/lib/mysql:rw
    env_file:
      - docker/etc/environment.yml
      - docker/etc/environment.development.yml

  #######################################
  # Storage
  #######################################
  storage:
    build:
      context: docker/storage/
    volumes:
      - /storage
